---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hzn-logs
  labels:
    app: hzn-core
    tier: storage
spec:
  storageClassName: standard
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
